### ISSUE TITLE
Constant Flickering

### ISSUE THREAD

**Issue by Linith** [janssen-io/foundry-macro-marker#7]
Hi,

I was attempting to use your module and all it does is cause all icons on both the GM side and the players side to lock out and flicker constantly. I tried your examples plus this even..
`let me = canvas.tokens.controlled[0];
MacroMarker.toggle(this, { entity: me });`
same results.
Disabled all mods except for yours and same thing happened again..
on Foundry 0.6.6 with dnd5e 0.96.

**Comment by janssen-io** [comment]
Initial errors came from incorrect use of the module, for future readers:

Do not use `MacroMarker.toggle` in the `Marker` tab of the macro. That code is being run often and should only return true (marker active) or false (marke inactive).
