### ISSUE TITLE
More conditional options

### ISSUE THREAD

**Issue by Cheolkeong** [janssen-io/foundry-macro-marker#9]
Hey there! I like the module a lot and am going to be using it heavily in my campaign. Thought it would be really neat if the color of the border could be determined dynamically based on logic. Perhaps having the return value be a color hex code? Would still be backwards compatible but perhaps in the `evaluateTrigger` function it checks for a hexcode instead of  `!!`? Or maybe it just does a straight pass-through without !! and whatever calls `evaluateTrigger` checks for a hexcode. idk.

I just want to be able to have spell macros glow pink for ready, blue for when a meta magic has been prepared, fade when expended. Or have normal attack actions have white, and when a rage boosts them they turn orange.

**Comment by janssen-io** [comment]
That is a great suggestion! 👍

**Comment by janssen-io** [comment]
This is a bit trickier than I initially thought, because markers are currently not updated if already active. But I'll figure something out. :)

**Comment by janssen-io** [comment]
Available in v1.0.5 🥳

**Comment by Cheolkeong** [comment]
Great stuff! Thanks again!
